### ISSUE TITLE
SyntaxError: Missing '[[;params.page]]'

### ISSUE THREAD

**Issue by urain39** [urain39/ijktpl.js#14]
造成原因分析：

因为token分析时会优先查找`[[:params.page]]`，而如果在当前Token处理是有使用`[[?token]]...[[;token]]`的写法会将同名的`[[;params.page]]`(第一个)token吃掉造成bug。

如：

```html
[[?token]]
  something1
[[;token]]
[[?token]]
  something2
[[:token]]
  something3
[[;token]]
```
第一个Token会被解读为包含something1和something2，然后在递归解析时会出现找不到`[[;token]]`的bug。

**Comment by urain39** [comment]
问题长开，但目测不会被修复。

**Comment by urain39** [comment]
解决方法：

手动加上空白的`[[:token]]`分支，此外不再建议使用不带else分之的写法。除非你能确定该变量只出现一次。

**Comment by uzilla** [comment]
获取内容以后通过thenBlock.split(tokenE)就可以解决了吧。。。

**Comment by uzilla** [comment]
fixed close later.

**Comment by uzilla** [comment]
IJKTPL的设计目标是使用简单易懂的代码实现一个轻量级但性能也并不差的模板引擎，所以设计上代码分析使用了递归但并没有使用递归下降分析。

**Comment by uzilla** [comment]
最新版上将语法预检查也删除了，DOM加载速度貌似有所提升。

**Comment by urain39** [comment]
@uzilla好像也没办法实现真正意义上递归下降分析吧(

**Comment by urain39** [comment]
迭代也有类似的越界查找的bug，目前已修复。
